-- Run this script in your Supabase SQL Editor to create the required tables

-- Disable RLS for all tables to prevent access issues if using anon key
-- If you want to use RLS, you will need to create appropriate policies.

-- 0. Create Colleges Table
CREATE TABLE IF NOT EXISTS colleges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  code TEXT NOT NULL
);
ALTER TABLE colleges DISABLE ROW LEVEL SECURITY;

-- 1. Create Departments Table
CREATE TABLE IF NOT EXISTS departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  code TEXT NOT NULL,
  college_id BIGINT REFERENCES colleges(id)
);
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;

-- 2. Create Faculty Table
CREATE TABLE IF NOT EXISTS faculty (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  full_name TEXT NOT NULL,
  faculty_code TEXT NOT NULL,
  department_id BIGINT NOT NULL REFERENCES departments(id),
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  status TEXT DEFAULT 'offline'
);
ALTER TABLE faculty DISABLE ROW LEVEL SECURITY;

-- 3. Create Students Table
CREATE TABLE IF NOT EXISTS students (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  course TEXT
);
ALTER TABLE students DISABLE ROW LEVEL SECURITY;

-- 4. Create Queue Table
CREATE TABLE IF NOT EXISTS queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id),
  faculty_id TEXT NOT NULL REFERENCES faculty(id),
  status TEXT DEFAULT 'waiting', -- waiting, next, serving, completed, cancelled
  entry_time TIMESTAMPTZ DEFAULT NOW(),
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  meet_link TEXT,
  source TEXT, -- kiosk, web
  purpose TEXT
);
ALTER TABLE queue DISABLE ROW LEVEL SECURITY;

-- 5. Insert some initial dummy data for testing (Optional)
INSERT INTO colleges (name, code)
VALUES
  ('College of Engineering', 'CEN'),
  ('College of Computer Studies', 'CCS'),
  ('College of Business Administration', 'CBA')
ON CONFLICT (name) DO NOTHING;

INSERT INTO students (id, name, email, course) 
VALUES 
  ('2021-0001', 'John Doe', 'john@example.com', 'BSCpE'),
  ('2021-0002', 'Jane Smith', 'jane@example.com', 'BSCpE')
ON CONFLICT (id) DO NOTHING;

-- 6. Insert Departments
INSERT INTO departments (name, code, college_id)
VALUES
  ('Computer Engineering', 'CpE', 1),
  ('Computer Science', 'CS', 2),
  ('Information Technology', 'IT', 2)
ON CONFLICT (name) DO NOTHING;

-- 7. Insert Faculty
INSERT INTO faculty (id, name, full_name, faculty_code, department_id, email, password, status)
VALUES
  ('fac-001', 'Dr. Alan Turing', 'Alan Mathison Turing', 'TURING-001', 1, 'aturing@earist.edu.ph', 'password123', 'available'),
  ('fac-002', 'Grace Hopper', 'Grace Brewster Murray Hopper', 'HOPPER-002', 2, 'ghopper@earist.edu.ph', 'password123', 'available'),
  ('fac-003', 'Ada Lovelace', 'Augusta Ada King, Countess of Lovelace', 'LOVELACE-003', 3, 'alovelace@earist.edu.ph', 'password123', 'offline')
ON CONFLICT (id) DO NOTHING;

-- If you get schema cache errors, run this command:
-- NOTIFY pgrst, 'reload schema';
